name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.tpl'
      - '**/*.py'
      - '**/*.tf'
      - '.github/workflows/release.yml'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

  insert_document:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install MongoDB driver
        run: npm install mongodb
      - name: Connect to MongoDB database
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          const { MongoClient } = require('mongodb');
          const client = new MongoClient(process.env.MONGO_URI, { useNewUrlParser: true });
          await client.connect();
          const db = client.db('my_database');
      - name: Insert document
        run: |
          const document = {
            name: 'My document',
            data: 'Some data'
          };
          await db.collection('my_collection').insertOne(document);
